### PR TITLE
Fix/task assignment add

### LINKED ISSUE #272: Who the task is assigned to at the time of creation is not saved

### PR DESCRIPTION
**Pull request by KianShirvani**
Saved the assigned users on the task creation

Added a line on the task cards to show who the task is assigned to

Closes #272

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -11,14 +11,26 @@ const getTasks = async (req, res) => {
...
+        const userRes = await client.query(
+          "SELECT user_id FROM task_users WHERE task_id = $1",
+          [task.task_id]
+        );
+        const assignedUsers = userRes.rows.map((row) => row.user_id);
+        return { ...task, assignedUsers };
+      })
+    );
+
+    res.status(200).json({ tasks });
```
Comment (kangnade) [inline backend/src/controllers/taskController.js:25]: Good fetch and update function for task_users table.

File: backend/src/controllers/taskController.js [hunk 2]
```diff
@@ -54,6 +66,17 @@ const createTask = async (req, res) => {
...
+      const { assignedUsers } = req.body;
+
+      if (assignedUsers && Array.isArray(assignedUsers)) {
+        const userPromises = assignedUsers.map((userId) =>
+          client.query("INSERT INTO task_users (task_id, user_id) VALUES ($1, $2)", [taskId, userId])
+        );
+        await Promise.all(userPromises);
+      }
+
+
```
Comment (kangnade) [inline backend/src/controllers/taskController.js:79]: Clean function that handles assignment of users to newly created task in task_users table

File: frontend/src/components/TaskList.js [hunk 3]
```diff
@@ -193,6 +194,17 @@ const TaskList = ({ title, tasks, onEditTask, onDeleteTask, onMoveTask, selected
...
+      <p><strong>Assigned To:</strong> {
+        task.assignedUsers
+          .map(userId => {
+            const user = availableUsers.find(u => u.id === userId || u.user_id === userId);
+            return user ? (user.display_name || `${user.first_name} ${user.last_name}`) : "Unknown";
+          })
+          .join(", ")
+      }</p>
+    )}
+
```
Comment (kangnade) [inline frontend/src/components/TaskList.js:207]: Clean function that displays the list of users assigned to a task in a readable format

**Review by kangnade — APPROVED** [review]
Review complete
