### PR TITLE
Fix progress not being able to be set to 0%

### LINKED ISSUE #258: Fix createTask not letting progress be at 0%
Description: When creating a task, can't set progress to 0%
Steps to reproduce: Create a task and try to set progress to 0%
Affected components: Tasks
Severity: Low

### PR DESCRIPTION
**Pull request by Rheiley**
- Progress bar can now be set to 0% when creating a task
- Added more enhanced error logging 
- Updated unit test to reflect the new error logging

Closes #258

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -24,10 +24,27 @@ const createTask = async (req, res) => {
...
+    }
+    if (!start_date) {
+      console.log("Missing required field: start_date", req.body);
+      return res.status(400).json({ message: "The 'start_date' field is required." });
+    }
+    if (!end_date) {
+      console.log("Missing required field: end_date", req.body);
+      return res.status(400).json({ message: "The 'end_date' field is required." });
+    }
+
```
Comment (KianShirvani) [inline backend/src/controllers/taskController.js:47]: Very clear and well written code to check any missing input fields when user is creating a task. Great work

File: backend/src/tests/task.test.js [hunk 2]
```diff
@@ -195,7 +195,7 @@ describe("POST /api/tasks", () => {
       .send(newTask);
 
     expect(res.statusCode).toBe(400);
-    expect(res.body).toHaveProperty("message", "All fields except status are required");
+    expect(res.body).toHaveProperty("message", "The 'title' field is required.");
```
Comment (KianShirvani) [inline backend/src/tests/task.test.js:198]: Good change for clarity

**Comment by KianShirvani** [comment]
Look good to merge. Resolves the issue as now progress bards can be set and updated to 0!
