### PR TITLE
Bugfix/align edit task

### LINKED ISSUE #233: Align edit task view to the Add Task view for scrollable feature
Description: "Edit Task" in TaskBoard and AdminDashboard should have the same scrollable view feature as when user creates new task by clicking "Add Task" button. Please also double check if the Add Task view is aligned in both TaskBoard and AdminDashboard.
Steps to reproduce: Go to /tasks page and try to add or edit a task. Both should have the same scrollable view.
Components affected: tasks, add task feature, update task feature
Severity: Moderate

### PR DESCRIPTION
**Pull request by KianShirvani**
Aligned edit task modal on admin dashboard to the edit task on the regular dashboard. Added scrolling feature and shrinked size

Closes #233

### CODE REVIEW

File: frontend/src/components/EditTaskModal.js [hunk 1]
```diff
@@ -1,69 +1,72 @@
-import React, { useState,  useEffect } from "react";
+import React, { useState, useEffect } from "react";
+
+const EditTaskModal = ({ task, onSave, onClose, availableUsers = [] }) => {
+  const formatDate = (date) => (date ? new Date(date).toISOString().split("T")[0] : "");
```
Comment (Rheiley) [inline frontend/src/components/EditTaskModal.js:4]: Good simplification of code, makes it more readable

File: frontend/src/components/EditTaskModal.js [hunk 2]
```diff
@@ -1,69 +1,72 @@
...
+    title: task.title || "",
+    description: task.description || "",
+    assignedUsers: task.assignedUsers || [],
+    priority: task.priority || "Medium",
+    dueDate: formatDate(task.due_date),
+    startDate: formatDate(task.start_date),
+    endDate: formatDate(task.end_date),
+    progress: task.progress || 0,
+    status: task.status || "to do",
+  });
```
Comment (Rheiley) [inline frontend/src/components/EditTaskModal.js:19]: Great usage of proper indentation to enhance code readability.

File: frontend/src/components/EditTaskModal.js [hunk 3]
```diff
@@ -1,69 +1,72 @@
...
+      assignedUsers: task.assignedUsers || [],
       priority: task.priority || "Medium",
-      dueDate: formatDate(task.due_date)|| "",
-      startDate: formatDate(task.start_date) || "", 
-      endDate: formatDate(task.end_date) || "", 
-      progress: task.progress || 0, 
+      dueDate: formatDate(task.due_date),
+      startDate: formatDate(task.start_date),
+      endDate: formatDate(task.end_date),
+      progress: task.progress || 0,
```
Comment (Rheiley) [inline frontend/src/components/EditTaskModal.js:33]: Good removal of redundant code since dates will never be empty

File: frontend/src/components/EditTaskModal.js [hunk 4]
```diff
@@ -169,33 +150,45 @@ const EditTaskModal = ({ task, onSave, onClose }) => {
 const styles = {
   overlay: {
     position: "fixed",
-    top: 0,
-    left: 0,
-    right: 0,
-    bottom: 0,
+    top: 0, left: 0, right: 0, bottom: 0,
```
Comment (Rheiley) [inline frontend/src/components/EditTaskModal.js:153]: Good condensation of code line usage

File: frontend/src/components/EditTaskModal.js [hunk 5]
```diff
@@ -216,7 +209,7 @@ const styles = {
     border: "none",
     cursor: "pointer",
     borderRadius: "5px",
-    fontSize: "16px",
+    fontSize: "14px",
   },
 };
```
Comment (Rheiley) [inline frontend/src/components/EditTaskModal.js:214]: Great edits to the CSS

**Review by Rheiley — APPROVED** [review]
Looks good to me! Ran the branch on my machine and the bug was fixed.
