### PR TITLE
Fix users not showing under 'assign users' field

### LINKED ISSUE #216: Ensure task dashboard can assign users to tasks (just like adminDashboard)

### PR DESCRIPTION
**Pull request by LZBTH16**
Changed the URL from the adminRoutes users, to the userRoutes users.

Closes #216

### CODE REVIEW

File: frontend/src/components/TaskBoard.js [hunk 1]
```diff
@@ -111,7 +111,7 @@ const TaskBoard = () => {
   // Fetch available users from the backend
   const fetchAvailableUsers = async () => {
     try {
-      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/admin/users`, {
+      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/users`, {
```
Comment (yanshuyu280042) [inline frontend/src/components/TaskBoard.js:114]: Nice path change.

**Review by yanshuyu280042 — APPROVED** [review]
