### PR TITLE
Fix messages redirect & clear auth token upon logout

### LINKED ISSUE #234: If not logged in, clicking on the messages icon should lead to login page, not sign up page
Description: When not logged in, going to messages takes to sign up page.
Steps to reproduce: Click on messages icon while not logged in.
Affected components: none
Severity: Low

### PR DESCRIPTION
**Pull request by LZBTH16**
- Changed the redirect from `/signup` to `/login` when trying to access /chat while not logged in.
- Cleared the token from local storage instead of setting it to log out to prevent access to `/tasks` when logged out.

Closes #234 #228

### CODE REVIEW

File: frontend/src/components/Header.js [hunk 1]
```diff
@@ -18,12 +18,12 @@ const Header = () => {
...
             navigate("/chat"); // Send to chat if logged in
         } else {
-            navigate("/signup"); // Redirect to sign-up if not logged in
+            navigate("/login"); // Redirect to sign-up if not logged in
         }
     };
 
     const handleLogout = () => {
-        localStorage.setItem("token", "logged_out");
+        localStorage.removeItem("token"); // remove authentication once logged out
```
Comment (yanshuyu280042) [inline frontend/src/components/Header.js:26]: Nice redirect to make the logic more clear.

**Review by yanshuyu280042 — APPROVED** [review]
