### PR TITLE
fixed scaling issue for adding task modal

### LINKED ISSUE #176: Fix scaling issue when creating new task
Ensure the "new task" pop-up is scrollable in cases where the user may be on a smaller screen.

Description: The "create new task" pop-up will be cut off on smaller screens, preventing proper task creation or closing out of the window.
Steps to reproduce: Go to /tasks while on a smaller resolution and click on "Add task". The pop-up window should be cut off, preventing the creation of new tasks or exiting out of that window.
Affected components: Add task within the taskboard
Severity: Moderate [affects smaller screen sizes]

### PR DESCRIPTION
**Pull request by KianShirvani**
Made add task modal shorter with a scroll bar and wider.

Closes #176

### CODE REVIEW

File: frontend/src/components/AddTask.js [hunk 1]
```diff
@@ -1,15 +1,14 @@
-import React, { useState,useEffect } from "react";
+import React, { useState, useEffect } from "react";
```
Comment (Rheiley) [inline frontend/src/components/AddTask.js:1]: Nice usage of consistent formatting when importing

File: frontend/src/components/AddTask.js [hunk 2]
```diff
@@ -25,21 +24,19 @@ const AddTask = ({ task, onSaveTask, onClose, availableUsers }) => {
...
         ...task,
-        // If editing, you might pre-populate assignedUsers if available in task
         assignedUsers: task.assignedUsers || [],
         dueDate: formatDateForInput(task.due_date),
         startDate: formatDateForInput(task.start_date),
         endDate: formatDateForInput(task.end_date),
       });
     }
   }, [task]);
+
```
Comment (Rheiley) [inline frontend/src/components/AddTask.js:34]: Good usage of spacing for improved code readability

File: frontend/src/components/AddTask.js [hunk 3]
```diff
@@ -48,73 +45,131 @@ const AddTask = ({ task, onSaveTask, onClose, availableUsers }) => {
...
+            value={taskData.assignedUsers}
+            onChange={handleAssignedUsersChange}
+            style={styles.input}
+          >
+            {availableUsers && availableUsers.map(user => (
+              <option key={user.id} value={user.id}>
+                {user.display_name || `${user.first_name} ${user.last_name}`}
+              </option>
+            ))}
+          </select>
```
Comment (Rheiley) [inline frontend/src/components/AddTask.js:66]: Good simplification of excess code

File: frontend/src/components/AddTask.js [hunk 4]
```diff
@@ -48,73 +45,131 @@ const AddTask = ({ task, onSaveTask, onClose, availableUsers }) => {
...
-          <option value="todo">To-Do</option>
-          <option value="inProgress">In Progress</option>
-          <option value="done">Done</option>
-        </select>
+          <label>Priority:</label>
+          <select name="priority" value={taskData.priority} onChange={handleChange} style={styles.input}>
+            <option>High</option>
+            <option>Medium</option>
+            <option>Low</option>
+          </select>
```
Comment (Rheiley) [inline frontend/src/components/AddTask.js:73]: Using priority instead of move to is a good change

File: frontend/src/components/AddTask.js [hunk 5]
```diff
@@ -48,73 +45,131 @@ const AddTask = ({ task, onSaveTask, onClose, availableUsers }) => {
...
+    width: "100%", 
+    padding: "10px", 
+    background: "#dc3545", 
+    color: "white", 
+    border: "none", 
+    cursor: "pointer", 
+    borderRadius: "5px", 
+    fontSize: "14px"
+  }
 };
```
Comment (Rheiley) [inline frontend/src/components/AddTask.js:173]: Great usage of better formatting for the CSS

**Review by Rheiley — APPROVED** [review]
Everything looks good to me.
