### PR TITLE
Fix/task assignment add

### LINKED ISSUE #272: Who the task is assigned to at the time of creation is not saved

### PR DESCRIPTION
**Pull request by KianShirvani**
Saved the assigned users on the task creation

Added a line on the task cards to show who the task is assigned to

Closes #272

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -11,14 +11,26 @@ const getTasks = async (req, res) => {
...
+        const userRes = await client.query(
+          "SELECT user_id FROM task_users WHERE task_id = $1",
+          [task.task_id]
+        );
+        const assignedUsers = userRes.rows.map((row) => row.user_id);
+        return { ...task, assignedUsers };
+      })
+    );
+
+    res.status(200).json({ tasks });
```
Comment (kangnade) [inline backend/src/controllers/taskController.js:25]: Good fix to ensure user id is incorporated when updating tasks.

File: frontend/src/components/TaskList.js [hunk 2]
```diff
@@ -193,6 +193,17 @@ const TaskList = ({ title, tasks, onEditTask, onDeleteTask, onMoveTask, selected
...
+      <p><strong>Assigned To:</strong> {
+        task.assignedUsers
+          .map(userId => {
+            const user = availableUsers.find(u => u.id === userId || u.user_id === userId);
+            return user ? (user.display_name || `${user.first_name} ${user.last_name}`) : "Unknown";
+          })
+          .join(", ")
+      }</p>
+    )}
+
```
Comment (kangnade) [inline frontend/src/components/TaskList.js:206]: nice fix

**Review by kangnade — APPROVED** [review]
Review complete
