### PR TITLE
Fixed issue #283, now when user Add Task via either TaskBoard or Admi…

### LINKED ISSUE #283: Userid is not being entered into the tasks table when user creates a task
Description: User id of the user creating the task does not get inserted into the tasks table.
Steps to reproduce: Go to taskboard and add a task while having the dev tools open. You will see in the console that the userid is not populated.
Components affected: task objects
Severity: Low (the site still functions as intended)

### PR DESCRIPTION
**Pull request by kangnade**
To close #283 
Now user create new tasks via the Add Task button (on both TaskBoard and AdminDashboard), the user_id column in tasks table in the database with be populated with the correct user_id.

### CODE REVIEW

File: frontend/src/components/TaskBoard.js [hunk 1]
```diff
@@ -215,6 +215,8 @@ useEffect(() => {
       progress: taskData.progress || 0,
       status: taskData.status || "todo",
       assignedUsers: taskData.assignedUsers || [],
+      // Fix bug: Set user_id to the first assigned user if available, otherwise null
+      user_id: taskData.assignedUsers && taskData.assignedUsers.length > 0 ? taskData.assignedUsers[0] : taskData.user_id,
```
Comment (yanshuyu280042) [inline frontend/src/components/TaskBoard.js:219]: Love this bug fix!

**Review by yanshuyu280042 — APPROVED** [review]
Works on my computer.
