### PR TITLE
Fix/task movement

### LINKED ISSUE #253: Tasks should be able to move columns correctly

### PR DESCRIPTION
**Pull request by KianShirvani**
Tasks now move properly. Fixed discrepancies for frontend and backend column names

Closes #253

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -97,7 +97,8 @@ const moveTask = async (req, res) => {
   try {
     const { taskId } = req.params;
     const { direction } = req.body;
-    const columnOrder = ["to do", "In Progress", "done"];
+    const columnOrder = ["todo", "in progress", "done"];
```
Comment (Rheiley) [inline backend/src/controllers/taskController.js:100]: Good choice to use lowercase to ensure consistency

File: frontend/src/components/TaskBoard.js [hunk 2]
```diff
@@ -522,17 +522,20 @@ useEffect(() => {
 
   return (
     <div style={styles.container}>
-      <div style={{ width: "100%", maxWidth: "800px", textAlign: "left", marginBottom: "10px" }}>
-        <h3>Welcome, {username}</h3>
+    <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "2vh", fontSize: "24px", marginTop: "10px" }}>
+    <h3>Welcome, {username}</h3>
+      </div>
+      <h1>Task Board</h1>
+      <div style={styles.addButtonWrapper}>
```
Comment (Rheiley) [inline frontend/src/components/TaskBoard.js:529]: Great usage of styles.addButtonWrapper rather than implicitly defining the CSS.

File: frontend/src/components/AdminDashboard.js [hunk 3]
```diff
@@ -582,8 +582,8 @@ const AdminDashboard = () => {
 
   return (
     <div className="admin-dashboard">
-      <div style={{ width: "100%", textAlign: "left", marginBottom: "10px", paddingLeft: "20px" }}>
-        <h3>Welcome, {username}</h3>
+    <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "2vh", fontSize: "24px", marginTop: "10px" }}>
```
Comment (Rheiley) [inline frontend/src/components/AdminDashboard.js:585]: Good refactoring of CSS

**Review by Rheiley — APPROVED** [review]
Looks good to me! Thanks for taking care of this issue.
