### PR TITLE
Fix users not being able to assign tasks

### LINKED ISSUE #229: Ensure assigned users are visible in their respective task cards

### PR DESCRIPTION
**Pull request by Rheiley**
- Users can now assign tasks to other users
- Users can also remove other users from assigned tasks
- Database is now correctly called (changed db to client)
- task_users table is now properly queried

Closes #229 #248

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -117,58 +117,97 @@ const moveTask = async (req, res) => {
...
+    if (priority !== undefined && isNaN(parsedPriority)) {
+      return res.status(400).json({ message: "Priority must be a valid integer" });
+    }
+
+    // Update task details
+    const result = await client.query(
+      "UPDATE tasks SET title=$1, description=$2, priority=$3, due_date=$4, start_date=$5, end_date=$6, progress=$7, status=$8 WHERE task_id=$9 RETURNING *",
+      [title, description, parsedPriority, due_date || null, start_date || null, end_date || null, progress, status, taskId]
+    );
+
```
Comment (KianShirvani) [inline backend/src/controllers/taskController.js:155]: Good code to update task

File: backend/src/controllers/taskController.js [hunk 2]
```diff
@@ -117,58 +117,97 @@ const moveTask = async (req, res) => {
...
+      const userPromises = assignedUsers.map((userId) =>
+        client.query("INSERT INTO task_users (task_id, user_id) VALUES ($1, $2)", [taskId, userId])
+      );
+      
+      // Wait for all insert operations to complete
+      await Promise.all(userPromises);
+    }
+
+    // Return the updated task
+    console.log(`Task ${taskId} updated successfully.`);
```
Comment (KianShirvani) [inline backend/src/controllers/taskController.js:175]: good checks for updating a teask to make sure it is assigned to a user

File: backend/src/controllers/taskController.js [hunk 3]
```diff
@@ -193,18 +232,55 @@ const updateAssignedTask = async (req, res) => {
...
+        const removePromises = usersToRemove.map(userId => {
+          return client.query(
+            "DELETE FROM task_users WHERE task_id = $1 AND user_id = $2",
+            [taskId, userId]
+          );
+        });
+        await Promise.all(removePromises);
+      }
+    }
+
```
Comment (KianShirvani) [inline backend/src/controllers/taskController.js:283]: Clear comments and code for assigning useres to tasks

File: frontend/src/components/AddTask.js [hunk 4]
```diff
@@ -22,156 +19,249 @@ const AddTask = ({ task, onSaveTask, onClose, availableUsers }) => {
...
+    setTaskData((prevData) => {
+      const isAlreadyAssigned = prevData.assignedUsers.includes(userId);
+      return {
+        ...prevData,
+        assignedUsers: isAlreadyAssigned
+          ? prevData.assignedUsers.filter((id) => id !== userId) // Remove user if already assigned
+          : [...prevData.assignedUsers, userId], // Add user if not assigned
+      };
+    });
   };
```
Comment (KianShirvani) [inline frontend/src/components/AddTask.js:68]: Good logic for displaying the correct users in the checkbox

**Comment by KianShirvani** [comment]
All good to merge I ran your branch on my machine and the code runs to resolve issue #229 #248
