### PR TITLE
Fix task movement

### LINKED ISSUE #188: Fix task movement between columns

### PR DESCRIPTION
**Pull request by Rheiley**
- TaskBoard.js and TaskList.js now correctly update the tasks on the frontend
- Fixed SQL queries in taskController.js
- Backend is now properly called

Closes #188

### CODE REVIEW

File: backend/src/controllers/taskController.js [hunk 1]
```diff
@@ -312,4 +312,3 @@ module.exports = {
   removeUsersFromTask,
   getFilteredTasks
 };
```
Comment (yanshuyu280042) [inline backend/src/controllers/taskController.js:314]: Great! Make sure the id matches the one in the database

File: frontend/src/components/TaskList.js [hunk 2]
```diff
@@ -1,16 +1,7 @@
...
-                    selectedColor, 
-                    onAssignColor,
-                    availableUsers,    // NEW: passed from TaskBoard
-                    onAddUser,         // NEW: function to add a user to a task
-                    onRemoveUser       // NEW: function to remove a user from a task
-                  }) => {
+import React, { useState, useEffect } from "react";
+import axios from "axios";
+
+const TaskList = ({ title, tasks, onEditTask, onDeleteTask, onMoveTask, selectedColor, onAssignColor, availableUsers, onAddUser, onRemoveUser }) => {
```
Comment (yanshuyu280042) [inline frontend/src/components/TaskList.js:4]: Good practice! Properly using axios.

File: frontend/src/components/TaskList.js [hunk 3]
```diff
@@ -102,6 +86,29 @@ const TaskList = ({ title,
...
+
+      if (response.status !== 200) throw new Error("Failed to move task");
+      console.log("Response data: ", response.data);
+      // Refresh the task list after moving the task
+      onMoveTask(task, direction);
+    } catch (error) {
+      console.error("Error moving task:", error);
+    }
+  };
+
```
Comment (yanshuyu280042) [inline frontend/src/components/TaskList.js:111]: Good job. Using handleMoveTask to make sure task movement between columns.

File: frontend/src/components/TaskList.js [hunk 4]
```diff
@@ -169,4 +175,4 @@ const userStyles = {
   addButton: { padding: "5px", cursor: "pointer" }
 };
 
-export default TaskList;
+export default TaskList;
```
Comment (yanshuyu280042) [inline frontend/src/components/TaskList.js:178]: Good changes in this file!

**Review by yanshuyu280042 — APPROVED** [review]
